### ISSUE TITLE
Support for new page format

### ISSUE THREAD

**Issue by tominkozhimala** [ptol/imdb-tv-series-chart#1]
Will the extension be updated to support the new format of the Titles page? There is an article detailing it here with a link to a preview: https://help.imdb.com/article/issues/GMWASETVPLJYXEZE

**Comment by ptol** [comment]
Yes, when they will release it.

**Comment by msnjuegos** [comment]
Is [this](https://user-images.githubusercontent.com/34399054/123004218-50d0c300-d382-11eb-9065-314091b43b56.png) the new format? I can't see the "View graph" option anymore.

**Comment by ptol** [comment]
@msnjuegos Yes. I have uploaded new version for chrome and firefox. Review process will take some time.

**Comment by ptol** [comment]
New version is available for firefox

**Comment by ptol** [comment]
And for chrome as well
