### ISSUE TITLE
Does not work with newer series

### ISSUE THREAD

**Issue by Myer** [ptol/imdb-tv-series-chart#15]
Some examples:
[https://www.imdb.com/title/tt14403178/](https://www.imdb.com/title/tt14403178/)
[https://www.imdb.com/title/tt10369484/](https://www.imdb.com/title/tt10369484/)
[https://www.imdb.com/title/tt12785720/](https://www.imdb.com/title/tt12785720/)

It still seems to work on older series, like:
[https://www.imdb.com/title/tt0944947/](https://www.imdb.com/title/tt0944947/)
[https://www.imdb.com/title/tt3581920/](https://www.imdb.com/title/tt3581920/)

The only difference I noticed is that those newer series have a 8-digit ID while the other have only 7 digits. Maybe it's a parsing issue? Or IMDb changed something again...

Tried it being logged-in and logged-out. Also cleared all cookies, local storage, etc,
This is with Firefox 112.0 (64-Bit) on Windows 10 (22H2).

**Comment by Myer** [comment]
Hm ok.... does not work here either and the ID only has 7-digits:
[https://www.imdb.com/title/tt3489184/](https://www.imdb.com/title/tt3489184/)

**Comment by ptol** [comment]
Hi. Thanks for your report. 
The problem was with one season shows. 
I have fixed it and everything should work in version 0.7

**Comment by Myer** [comment]
That was fast, thanks a lot!
