### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by ks1v** [ptol/imdb-tv-series-chart#16]
Extension has stopped working recently: just endless spinning wheel instead of a chart

version 0.9
Firefox 131.0 (64-bit)
macOS 14.6.1 (23G93)

<img width="1716" alt="image" src="https://github.com/user-attachments/assets/10406f7f-1aa9-4471-97be-443b4dc2be73">

**Comment by ptol** [comment]
Thanks for the report. Should work in version 0.10

**Comment by ks1v** [comment]
thanks!
